// <auto-generated />
using System;
using InnovationToImpact.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InnovationToImpact.Infrastructure.Migrations
{
    [DbContext(typeof(InnovationDbContext))]
    [Migration("20260714124541_AddIpKnowledgeSlice")]
    partial class AddIpKnowledgeSlice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Activities", (string)null);
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.AdminSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.HasIndex("UpdatedById");

                    b.ToTable("AdminSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Key = "top_n",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueJson = "5"
                        },
                        new
                        {
                            Key = "pass_threshold",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueJson = "7"
                        });
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AssignedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignmentStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EvaluatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdeaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedById");

                    b.HasIndex("AssignmentStatusId");

                    b.HasIndex("IdeaId");

                    b.HasIndex("EvaluatorId", "AssignmentStatusId");

                    b.ToTable("Assignments", (string)null);
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.AssignmentStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AssignmentStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            Code = "pending",
                            NameAr = "معلّق",
                            NameEn = "Pending",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            Code = "completed",
                            NameAr = "مكتمل",
                            NameEn = "Completed",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            Code = "declined",
                            NameAr = "مرفوض",
                            NameEn = "Declined",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.Benefit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BenefitCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BenefitTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvidenceJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdeaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("MeasurementDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MeasurementUnit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("RealizedValue")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)");

                    b.Property<decimal?>("TargetValue")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("VerifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BenefitCategoryId");

                    b.HasIndex("BenefitTypeId");

                    b.HasIndex("IdeaId");

                    b.HasIndex("VerifiedById");

                    b.ToTable("Benefits", (string)null);
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.BenefitCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("BenefitCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0006-000000000001"),
                            Code = "financial",
                            NameAr = "مالي",
                            NameEn = "Financial",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0006-000000000002"),
                            Code = "operational",
                            NameAr = "تشغيلي",
                            NameEn = "Operational",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0006-000000000003"),
                            Code = "social",
                            NameAr = "اجتماعي",
                            NameEn = "Social",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0006-000000000004"),
                            Code = "strategic",
                            NameAr = "استراتيجي",
                            NameEn = "Strategic",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.BenefitType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("BenefitTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000001"),
                            Code = "quantitative",
                            NameAr = "كمي",
                            NameEn = "Quantitative",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000002"),
                            Code = "qualitative",
                            NameAr = "نوعي",
                            NameEn = "Qualitative",
                            SortOrder = 2
                        });
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.CommitteeCriterion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CommitteeCriteria", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000001"),
                            Active = true,
                            Code = "originality",
                            NameAr = "الأصالة",
                            NameEn = "Originality",
                            Weight = 0.30m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000002"),
                            Active = true,
                            Code = "feasibility",
                            NameAr = "قابلية التنفيذ",
                            NameEn = "Feasibility",
                            Weight = 0.25m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000003"),
                            Active = true,
                            Code = "impact",
                            NameAr = "الأثر",
                            NameEn = "Impact",
                            Weight = 0.30m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000004"),
                            Active = true,
                            Code = "alignment",
                            NameAr = "التوافق الاستراتيجي",
                            NameEn = "Strategic Alignment",
                            Weight = 0.15m
                        });
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.CommitteeDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttachmentsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("CommitteeDecisionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommitteeName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DecidedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdeaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("QuorumMet")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CommitteeDecisionTypeId");

                    b.HasIndex("DecidedById");

                    b.HasIndex("IdeaId");

                    b.ToTable("CommitteeDecisions", (string)null);
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.CommitteeDecisionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CommitteeDecisionTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000001"),
                            Code = "approved",
                            NameAr = "معتمد",
                            NameEn = "Approved",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000002"),
                            Code = "rejected",
                            NameAr = "مرفوض",
                            NameEn = "Rejected",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000003"),
                            Code = "deferred",
                            NameAr = "مؤجل",
                            NameEn = "Deferred",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.Evaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comments")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("ConflictOfInterest")
                        .HasColumnType("bit");

                    b.Property<string>("CriteriaScoresJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EvaluatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdeaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Recommendation")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalScore")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluatorId");

                    b.HasIndex("IdeaId", "EvaluatorId")
                        .IsUnique();

                    b.ToTable("Evaluations", (string)null);
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.EvaluatorTrackAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvaluatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssignedById");

                    b.HasIndex("TrackId");

                    b.HasIndex("EvaluatorId", "TrackId")
                        .IsUnique();

                    b.ToTable("EvaluatorTrackAssignments", (string)null);
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.FundingRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmountSar")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)");

                    b.Property<decimal?>("ApprovedAmount")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)");

                    b.Property<Guid?>("ApproverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FundingStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdeaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JustificationAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JustificationEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("FundingStatusId");

                    b.HasIndex("IdeaId");

                    b.ToTable("FundingRequests", (string)null);
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.FundingStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("FundingStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0007-000000000001"),
                            Code = "pending",
                            NameAr = "قيد الانتظار",
                            NameEn = "Pending",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0007-000000000002"),
                            Code = "approved",
                            NameAr = "معتمد",
                            NameEn = "Approved",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0007-000000000003"),
                            Code = "rejected",
                            NameAr = "مرفوض",
                            NameEn = "Rejected",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0007-000000000004"),
                            Code = "partially_approved",
                            NameAr = "معتمد جزئياً",
                            NameEn = "Partially Approved",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.HandoverStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("HandoverStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0009-000000000001"),
                            Code = "pending",
                            NameAr = "قيد الانتظار",
                            NameEn = "Pending",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0009-000000000002"),
                            Code = "in_progress",
                            NameAr = "قيد التنفيذ",
                            NameEn = "In Progress",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0009-000000000003"),
                            Code = "completed",
                            NameAr = "مكتمل",
                            NameEn = "Completed",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.Idea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStage")
                        .HasColumnType("int");

                    b.Property<string>("ExpectedBenefitsAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpectedBenefitsEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdeaStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProblemStatementAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemStatementEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProposedSolutionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProposedSolutionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StrategicThemeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubmitterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IdeaStatusId");

                    b.HasIndex("StrategicThemeId");

                    b.HasIndex("SubmitterId");

                    b.ToTable("Ideas", null, t =>
                        {
                            t.HasCheckConstraint("CK_Ideas_CurrentStage", "[CurrentStage] >= 0 AND [CurrentStage] <= 8");
                        });
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.IdeaStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("IdeaStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Code = "draft",
                            NameAr = "مسودة",
                            NameEn = "Draft",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Code = "submitted",
                            NameAr = "مُقدَّمة",
                            NameEn = "Submitted",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Code = "screening",
                            NameAr = "قيد الفرز",
                            NameEn = "Screening",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Code = "needs_completion",
                            NameAr = "بحاجة لإكمال",
                            NameEn = "Needs Completion",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Code = "evaluation",
                            NameAr = "قيد التقييم",
                            NameEn = "Evaluation",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Code = "committee",
                            NameAr = "قيد اللجنة",
                            NameEn = "Committee",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Code = "approved",
                            NameAr = "معتمدة",
                            NameEn = "Approved",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Code = "rejected",
                            NameAr = "مرفوضة",
                            NameEn = "Rejected",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Code = "returned",
                            NameAr = "معادة",
                            NameEn = "Returned",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Code = "assigned",
                            NameAr = "مسندة",
                            NameEn = "Assigned",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Code = "in_pilot",
                            NameAr = "قيد التجريب",
                            NameEn = "In Pilot",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Code = "in_implementation",
                            NameAr = "قيد التنفيذ",
                            NameEn = "In Implementation",
                            SortOrder = 12
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            Code = "benefits_tracking",
                            NameAr = "تتبع المنافع",
                            NameEn = "Benefits Tracking",
                            SortOrder = 13
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            Code = "closed",
                            NameAr = "مغلقة",
                            NameEn = "Closed",
                            SortOrder = 14
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            Code = "archived",
                            NameAr = "مؤرشفة",
                            NameEn = "Archived",
                            SortOrder = 15
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            Code = "withdrawn",
                            NameAr = "مسحوبة",
                            NameEn = "Withdrawn",
                            SortOrder = 16
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            Code = "pass_awaiting_attachments",
                            NameAr = "بانتظار المرفقات",
                            NameEn = "Pass Awaiting Attachments",
                            SortOrder = 17
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            Code = "pending_final_ranking",
                            NameAr = "بانتظار الترتيب النهائي",
                            NameEn = "Pending Final Ranking",
                            SortOrder = 18
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            Code = "evaluation_failed",
                            NameAr = "فشل التقييم",
                            NameEn = "Evaluation Failed",
                            SortOrder = 19
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            Code = "not_selected",
                            NameAr = "لم يتم اختيارها",
                            NameEn = "Not Selected",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            Code = "in_measurement",
                            NameAr = "قيد القياس",
                            NameEn = "In Measurement",
                            SortOrder = 21
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            Code = "in_scaling",
                            NameAr = "قيد التوسّع",
                            NameEn = "In Scaling",
                            SortOrder = 22
                        });
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.Implementation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HandoverStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdeaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IntegrationPlanAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntegrationPlanEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LineUnit")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OperationalOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResourceCommitmentAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResourceCommitmentEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HandoverStatusId");

                    b.HasIndex("IdeaId");

                    b.HasIndex("OperationalOwnerId");

                    b.ToTable("Implementations", (string)null);
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.IpRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConfidentialityTermsAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfidentialityTermsEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdeaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IpTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("NdaRequired")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NdaSignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OwnershipPartyAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnershipPartyEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParticipationConditionsAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParticipationConditionsEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdeaId");

                    b.HasIndex("IpTypeId");

                    b.ToTable("IpRecords", (string)null);
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.IpSignature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdeaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IpTermsVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("SignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("IdeaId", "UserId")
                        .IsUnique();

                    b.ToTable("IpSignatures", (string)null);
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.IpType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("IpTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0010-000000000001"),
                            Code = "patent",
                            NameAr = "براءة اختراع",
                            NameEn = "Patent",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0010-000000000002"),
                            Code = "trademark",
                            NameAr = "علامة تجارية",
                            NameEn = "Trademark",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0010-000000000003"),
                            Code = "copyright",
                            NameAr = "حقوق النشر",
                            NameEn = "Copyright",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0010-000000000004"),
                            Code = "trade_secret",
                            NameAr = "سر تجاري",
                            NameEn = "Trade Secret",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.KnowledgeArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentMdAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentMdEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdeaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KnowledgeTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KnowledgeVisibilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceLabelAr")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("SourceLabelEn")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("TagsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("IdeaId");

                    b.HasIndex("KnowledgeTypeId");

                    b.HasIndex("KnowledgeVisibilityId");

                    b.ToTable("KnowledgeArticles", (string)null);
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.KnowledgeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("KnowledgeTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0011-000000000001"),
                            Code = "article",
                            NameAr = "مقال",
                            NameEn = "Article",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0011-000000000002"),
                            Code = "case_study",
                            NameAr = "دراسة حالة",
                            NameEn = "Case Study",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0011-000000000003"),
                            Code = "template",
                            NameAr = "نموذج",
                            NameEn = "Template",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0011-000000000004"),
                            Code = "official_guide",
                            NameAr = "دليل رسمي",
                            NameEn = "Official Guide",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.KnowledgeVisibility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("KnowledgeVisibilities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0012-000000000001"),
                            Code = "public",
                            NameAr = "عام",
                            NameEn = "Public",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0012-000000000002"),
                            Code = "internal",
                            NameAr = "داخلي",
                            NameEn = "Internal",
                            SortOrder = 2
                        });
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.Pilot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Budget")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExperimentPlanAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExperimentPlanEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HypothesisAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HypothesisEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdeaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LessonsLearnedAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LessonsLearnedEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MilestonesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PilotStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResultsAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultsEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdeaId");

                    b.HasIndex("PilotStatusId");

                    b.ToTable("Pilots", (string)null);
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.PilotStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PilotStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000001"),
                            Code = "planned",
                            NameAr = "مخطط له",
                            NameEn = "Planned",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000002"),
                            Code = "in_progress",
                            NameAr = "قيد التنفيذ",
                            NameEn = "In Progress",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000003"),
                            Code = "completed",
                            NameAr = "مكتمل",
                            NameEn = "Completed",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000004"),
                            Code = "cancelled",
                            NameAr = "ملغى",
                            NameEn = "Cancelled",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.ScaleDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DecidedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EvidenceOfViabilityAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvidenceOfViabilityEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdeaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RiskAssessmentAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RiskAssessmentEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ScaleDecisionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("StrategicFitScore")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("ValueAssessmentAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValueAssessmentEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DecidedById");

                    b.HasIndex("IdeaId");

                    b.HasIndex("ScaleDecisionTypeId");

                    b.ToTable("ScaleDecisions", (string)null);
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.ScaleDecisionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ScaleDecisionTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000001"),
                            Code = "scale",
                            NameAr = "توسيع",
                            NameEn = "Scale",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000002"),
                            Code = "hold",
                            NameAr = "تعليق",
                            NameEn = "Hold",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000003"),
                            Code = "reject",
                            NameAr = "رفض",
                            NameEn = "Reject",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.StrategicTheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("StrategicThemes", (string)null);
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FullNameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullNameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("ManagerEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("SamAccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("SamAccountName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.Activity", b =>
                {
                    b.HasOne("InnovationToImpact.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.AdminSetting", b =>
                {
                    b.HasOne("InnovationToImpact.Domain.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.Assignment", b =>
                {
                    b.HasOne("InnovationToImpact.Domain.Entities.User", "AssignedBy")
                        .WithMany()
                        .HasForeignKey("AssignedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InnovationToImpact.Domain.Entities.AssignmentStatus", "AssignmentStatus")
                        .WithMany()
                        .HasForeignKey("AssignmentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InnovationToImpact.Domain.Entities.User", "Evaluator")
                        .WithMany()
                        .HasForeignKey("EvaluatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InnovationToImpact.Domain.Entities.Idea", "Idea")
                        .WithMany()
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedBy");

                    b.Navigation("AssignmentStatus");

                    b.Navigation("Evaluator");

                    b.Navigation("Idea");
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.Benefit", b =>
                {
                    b.HasOne("InnovationToImpact.Domain.Entities.BenefitCategory", "BenefitCategory")
                        .WithMany()
                        .HasForeignKey("BenefitCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InnovationToImpact.Domain.Entities.BenefitType", "BenefitType")
                        .WithMany()
                        .HasForeignKey("BenefitTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InnovationToImpact.Domain.Entities.Idea", "Idea")
                        .WithMany()
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InnovationToImpact.Domain.Entities.User", "VerifiedBy")
                        .WithMany()
                        .HasForeignKey("VerifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BenefitCategory");

                    b.Navigation("BenefitType");

                    b.Navigation("Idea");

                    b.Navigation("VerifiedBy");
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.CommitteeDecision", b =>
                {
                    b.HasOne("InnovationToImpact.Domain.Entities.CommitteeDecisionType", "CommitteeDecisionType")
                        .WithMany()
                        .HasForeignKey("CommitteeDecisionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InnovationToImpact.Domain.Entities.User", "DecidedBy")
                        .WithMany()
                        .HasForeignKey("DecidedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InnovationToImpact.Domain.Entities.Idea", "Idea")
                        .WithMany()
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommitteeDecisionType");

                    b.Navigation("DecidedBy");

                    b.Navigation("Idea");
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.Evaluation", b =>
                {
                    b.HasOne("InnovationToImpact.Domain.Entities.User", "Evaluator")
                        .WithMany()
                        .HasForeignKey("EvaluatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InnovationToImpact.Domain.Entities.Idea", "Idea")
                        .WithMany()
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluator");

                    b.Navigation("Idea");
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.EvaluatorTrackAssignment", b =>
                {
                    b.HasOne("InnovationToImpact.Domain.Entities.User", "AssignedBy")
                        .WithMany()
                        .HasForeignKey("AssignedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InnovationToImpact.Domain.Entities.User", "Evaluator")
                        .WithMany()
                        .HasForeignKey("EvaluatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InnovationToImpact.Domain.Entities.StrategicTheme", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedBy");

                    b.Navigation("Evaluator");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.FundingRequest", b =>
                {
                    b.HasOne("InnovationToImpact.Domain.Entities.User", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InnovationToImpact.Domain.Entities.FundingStatus", "FundingStatus")
                        .WithMany()
                        .HasForeignKey("FundingStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InnovationToImpact.Domain.Entities.Idea", "Idea")
                        .WithMany()
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("FundingStatus");

                    b.Navigation("Idea");
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.Idea", b =>
                {
                    b.HasOne("InnovationToImpact.Domain.Entities.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InnovationToImpact.Domain.Entities.IdeaStatus", "IdeaStatus")
                        .WithMany()
                        .HasForeignKey("IdeaStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InnovationToImpact.Domain.Entities.StrategicTheme", "StrategicTheme")
                        .WithMany()
                        .HasForeignKey("StrategicThemeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InnovationToImpact.Domain.Entities.User", "Submitter")
                        .WithMany()
                        .HasForeignKey("SubmitterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("IdeaStatus");

                    b.Navigation("StrategicTheme");

                    b.Navigation("Submitter");
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.Implementation", b =>
                {
                    b.HasOne("InnovationToImpact.Domain.Entities.HandoverStatus", "HandoverStatus")
                        .WithMany()
                        .HasForeignKey("HandoverStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InnovationToImpact.Domain.Entities.Idea", "Idea")
                        .WithMany()
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InnovationToImpact.Domain.Entities.User", "OperationalOwner")
                        .WithMany()
                        .HasForeignKey("OperationalOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HandoverStatus");

                    b.Navigation("Idea");

                    b.Navigation("OperationalOwner");
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.IpRecord", b =>
                {
                    b.HasOne("InnovationToImpact.Domain.Entities.Idea", "Idea")
                        .WithMany()
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InnovationToImpact.Domain.Entities.IpType", "IpType")
                        .WithMany()
                        .HasForeignKey("IpTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Idea");

                    b.Navigation("IpType");
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.IpSignature", b =>
                {
                    b.HasOne("InnovationToImpact.Domain.Entities.Idea", "Idea")
                        .WithMany()
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InnovationToImpact.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idea");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.KnowledgeArticle", b =>
                {
                    b.HasOne("InnovationToImpact.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InnovationToImpact.Domain.Entities.Idea", "Idea")
                        .WithMany()
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InnovationToImpact.Domain.Entities.KnowledgeType", "KnowledgeType")
                        .WithMany()
                        .HasForeignKey("KnowledgeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InnovationToImpact.Domain.Entities.KnowledgeVisibility", "KnowledgeVisibility")
                        .WithMany()
                        .HasForeignKey("KnowledgeVisibilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Idea");

                    b.Navigation("KnowledgeType");

                    b.Navigation("KnowledgeVisibility");
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.Pilot", b =>
                {
                    b.HasOne("InnovationToImpact.Domain.Entities.Idea", "Idea")
                        .WithMany()
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InnovationToImpact.Domain.Entities.PilotStatus", "PilotStatus")
                        .WithMany()
                        .HasForeignKey("PilotStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Idea");

                    b.Navigation("PilotStatus");
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.ScaleDecision", b =>
                {
                    b.HasOne("InnovationToImpact.Domain.Entities.User", "DecidedBy")
                        .WithMany()
                        .HasForeignKey("DecidedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InnovationToImpact.Domain.Entities.Idea", "Idea")
                        .WithMany()
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InnovationToImpact.Domain.Entities.ScaleDecisionType", "ScaleDecisionType")
                        .WithMany()
                        .HasForeignKey("ScaleDecisionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DecidedBy");

                    b.Navigation("Idea");

                    b.Navigation("ScaleDecisionType");
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.StrategicTheme", b =>
                {
                    b.HasOne("InnovationToImpact.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("InnovationToImpact.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InnovationToImpact.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InnovationToImpact.Domain.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
